### ISSUE TITLE
run_qunit.js can't work correctly

### ISSUE THREAD

**Issue by ghost** [metaodi/GFTPrototype#1]
odi86:

```
 Hi ! 

Recently i'm working on js unit test research,  at last i decided to use phantomjs to run unit test

so, i found your run_qunit.js source , i check it out and run it  below  command:

phantomjs run_qunit.js http://{myhost}/qunit.html  // the qunit.html is from qunit offical example, 

result below :
```
# 

<?xml version="1.0"?>
&lt;!--
 Tests completed in 22 milliseconds.
5 tests of 6 passed, 1 failed.
--&gt;
&lt;testsuite name="QUnit - JavaScript Tests" timestamp="2012-04-20T02:16:26Z" tests="6" failures="1" time="0.022"&gt;
&lt;/testsuite&gt;
# 

   it can't show the passed and the failed test case.   Did you run correctly ?

**Comment by metaodi** [comment]
Thank you for your issue. Actually I never tested my script with the example from the QUnit example. I already figured out what the problem is: I assume that there is always a module for a test, and with my current script, the module may not contain _spaces_. I'll fix it in a minute :-)
